sudo: required

language: node_js

compiler: gcc

node_js:
  - 9

cache: yarn

services:
  - docker

before_install:
  - node -v
  - yarn -v
  - npm i -g lerna
  # postgres
  - createdb sqlectron
  - psql -d sqlectron -a -f test/databases/postgresql/schema/schema.sql
  # mysql
  - mysql -e "create database sqlectron;" --user=root
  - mysql sqlectron < test/databases/mysql/schema/schema.sql --user=root
  # sqlserver
  # - sqlcmd -S localhost,1433 -U sa -P Password12! -Q "CREATE DATABASE sqlectron" -d "master"
  # - sqlcmd -S localhost,1433 -U sa -P Password12! -i test/databases/sqlserver/schema/schema.sql -d "sqlectron"
  # - sqlcmd -S localhost,1433 -U sa -P Password12! -Q "select table_name from information_schema.tables" -d "sqlectron"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.7
      - g++-4.7

script:
  - lerna bootstrap
  - lerna run build
  - lerna run test
  - yarn coverage

after_script:
  - yarn coveralls
